title: Ali ALMASI
logo:  # you can add own logo.
description:
baseurl: ""
url: https://ali-almasi.github.io # the base hostname & protocol for your site, e.g. http://example.com


# Author Settings
author:
  name: Ali ALMASI
  image: '/assets/img/profile.jpg'
  job: Ali ALMASI
  bio: |+
        <p>
            I am a PhD-track computer science student currently enrolled in the second year of the MPRI (Master Parisien de Recherche en Informatique) at École Polytechnique, part of the Institut Polytechnique de Paris. I previously completed my undergraduate studies at Sharif University of Technology, where I earned a bachelor's degree in mathematics with a minor in computer science.
        </p>
        <p>
            My primary field of interest is quantum information science, with a particular focus on using methods from optimization theory and mathematical analysis to tackle problems in quantum information theory.
        </p>
  email: ali.almasi@polytechnique.edu
  resume: https://ali-almasi.github.io/curriculum-vitae
  
  github: https://github.com/ali-almasi
  
  twitter: https://twitter.com/leakingboat
  linkedin: https://www.linkedin.com/in/ali-almasi-43a44225a/
  saatchiart: https://www.saatchiart.com/alialmasi
  last_update:  April 2024  




# Contact links
contact:
  
  # - name: Instagram
  #   link: https://instagram.com/

# Comment Section (Disqus)
disqus-identifier: ali-almasi-personal
 # add your shortname for Disqus Comment. For example mr-brown


# Google Analytics
google-analytics: G-EN75K7EYQ3
# add your identifier. For example UA-99631805-1.


# Build settings
markdown: kramdown
permalink: pretty
plugins:
  - jekyll-sitemap
  - jekyll/tagging

# Pages Path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext

include:
  - _pages

# Tags
tag_page_dir:         tag
tag_page_layout:      tag-page
tag_permalink_style:  pretty

sass:
  sass_dir: _sass
  style: compressed


# Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
