title: "Ali Almasi"
author: "Ali Almasi"
description: "“Great things are not done by impulse, but by a series of small things brought together.” -Attributed to Vincent van Gogh
"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: false        # show article excerpts on the home page
show_frame: true          # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header
minimal: false             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "index.html", title: "About Me"}
  - {file: "CV.md", title: "CV"}
  - {file: "projects.md", title: "Projects"}
  - {file: "teaching.md", title: "Teaching"}
  # - {file: "talks.md", title: "Talks"}
  - {file: "blog.html", title: "Blog"}

  

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "mailto:ali.almasi@polytechnique.edu"}
  - {title: Github, icon: github, url: "https://github.com/ali-almasi"}
  - {title: Twitter, icon: twitter, url: "https://twitter.com/leakingboat"}
  - {title: Pinterest, icon: pinterest, url: "https://www.pinterest.fr/ali79almasi/_created"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
